/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import dao.admin;
import javax.swing.JOptionPane;

/**
 *
 * @author HAFIZ TECH
 */
public class adminDetails extends javax.swing.JFrame {
    public String username;
    /**
     * Creates new form adminDetails
     */
    public adminDetails() {
        initComponents();  
       
    }
    public adminDetails(admin a) {
        initComponents();
        
        username = a.getUsername();
        tid.setText(""+a.getId());
        tusername.setText(a.getUsername());
        tname.setText(a.getName());
        temail.setText(a.getEmail());
        tphoneno.setText(a.getPhonenumber());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        tname5 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        tname6 = new javax.swing.JLabel();
        tname7 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        tusername = new javax.swing.JLabel();
        tname = new javax.swing.JLabel();
        temail = new javax.swing.JLabel();
        tphoneno = new javax.swing.JLabel();
        tphoneno3 = new javax.swing.JLabel();
        tname4 = new javax.swing.JLabel();
        tid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 0, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 0));

        tname5.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        tname5.setText("User Name:");

        t1.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        t1.setText("Name:");

        tname6.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        tname6.setText("Phone Number:");

        tname7.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        tname7.setText("Email:");

        btnRegister.setBackground(new java.awt.Color(255, 233, 57));
        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegister.setText("click");
        btnRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        tusername.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        tusername.setText("username");

        tname.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        tname.setText("name");

        temail.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        temail.setText("email");

        tphoneno.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        tphoneno.setText("phone");

        tphoneno3.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        tphoneno3.setText("Change password?");

        tname4.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        tname4.setText("Your ID:");

        tid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tid.setText("id");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(tphoneno3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t1)
                                    .addComponent(tname5)
                                    .addComponent(jLabel1))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(tname7)
                                    .addGap(64, 64, 64)))
                            .addComponent(tname6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tphoneno)
                            .addComponent(tusername)
                            .addComponent(tname)
                            .addComponent(temail))))
                .addGap(139, 139, 139))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(tname4)
                .addGap(49, 49, 49)
                .addComponent(tid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tname4)
                            .addComponent(tid)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addGap(40, 40, 40)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tname5)
                    .addComponent(tusername))
                .addGap(27, 27, 27)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1)
                    .addComponent(tname))
                .addGap(36, 36, 36)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tname7)
                    .addComponent(temail))
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tname6)
                    .addComponent(tphoneno))
                .addGap(43, 43, 43)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tphoneno3)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        changePassword cp = new changePassword(username, false);
        cp.setVisible(true);
        //        dispose();
        //        int id = Integer.parseInt(tid.getText().toString());
        //
        //        String newPrice = newprice.getText().trim();
        //        if (newPrice.equals("")){
            //            JOptionPane.showMessageDialog(this, "Username and Password Should Not be Empty.", "Message", JOptionPane.ERROR_MESSAGE);
            //        }
        //        else{
            //            int a = JOptionPane.showConfirmDialog(null, "New price will be "+newprice.getText()+" ?","Select",JOptionPane.YES_NO_OPTION);
            //            if (a == 0){
                //                userDao.updatePrice(newPrice, id);
                //                clear();
                //            }
            //
            //        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegister8;
    private javax.swing.JButton btnRegister9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel10;
    private keeptoo.KGradientPanel kGradientPanel9;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    private javax.swing.JLabel temail;
    private javax.swing.JLabel temail8;
    private javax.swing.JLabel temail9;
    private javax.swing.JLabel tid;
    private javax.swing.JLabel tid8;
    private javax.swing.JLabel tid9;
    private javax.swing.JLabel tname;
    private javax.swing.JLabel tname4;
    private javax.swing.JLabel tname40;
    private javax.swing.JLabel tname41;
    private javax.swing.JLabel tname42;
    private javax.swing.JLabel tname43;
    private javax.swing.JLabel tname44;
    private javax.swing.JLabel tname45;
    private javax.swing.JLabel tname46;
    private javax.swing.JLabel tname47;
    private javax.swing.JLabel tname48;
    private javax.swing.JLabel tname49;
    private javax.swing.JLabel tname5;
    private javax.swing.JLabel tname6;
    private javax.swing.JLabel tname7;
    private javax.swing.JLabel tphoneno;
    private javax.swing.JLabel tphoneno16;
    private javax.swing.JLabel tphoneno17;
    private javax.swing.JLabel tphoneno18;
    private javax.swing.JLabel tphoneno19;
    private javax.swing.JLabel tphoneno3;
    private javax.swing.JLabel tusername;
    private javax.swing.JLabel tusername8;
    private javax.swing.JLabel tusername9;
    // End of variables declaration//GEN-END:variables
}
