/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import model.user;

/**
 *
 * @author Lenovo
 */
public class userDetails extends javax.swing.JFrame {

    /**
     * Creates new form userDetails
     */
    public String  username;
     public userDetails() {
        initComponents();
     }
    public userDetails(user u) {
        initComponents();
        username = u.getUsername();
        tid.setText(""+u.getId());
        tusername.setText(u.getUsername());
        tname.setText(u.getName());
        temail.setText(u.getEmail());
        tphoneno.setText(u.getPhonenumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        tname1 = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        tname2 = new javax.swing.JLabel();
        tname3 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        tusername = new javax.swing.JLabel();
        tname = new javax.swing.JLabel();
        temail = new javax.swing.JLabel();
        tphoneno = new javax.swing.JLabel();
        tname4 = new javax.swing.JLabel();
        tid = new javax.swing.JLabel();
        tphoneno1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 0, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 0));

        tname1.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        tname1.setText("User Name:");

        t.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        t.setText("Name:");

        tname2.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        tname2.setText("Phone Number:");

        tname3.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        tname3.setText("Email:");

        btnRegister.setBackground(new java.awt.Color(255, 233, 57));
        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegister.setText("click");
        btnRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        tusername.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        tusername.setText("username");

        tname.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        tname.setText("name");

        temail.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        temail.setText("email");

        tphoneno.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        tphoneno.setText("phone");

        tname4.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        tname4.setText("Your ID:");

        tid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tid.setText("id");

        tphoneno1.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        tphoneno1.setText("Change password?");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(tphoneno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tname2)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t)
                                    .addComponent(tname1))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(tname3)
                                    .addGap(64, 64, 64))))
                        .addGap(21, 21, 21)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tname)
                            .addComponent(tusername)
                            .addComponent(temail)
                            .addComponent(tphoneno))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(tname4)
                .addGap(30, 30, 30)
                .addComponent(tid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tname4)
                            .addComponent(tid)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(49, 49, 49)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tname1)
                    .addComponent(tusername))
                .addGap(27, 27, 27)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t)
                    .addComponent(tname))
                .addGap(36, 36, 36)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tname3)
                    .addComponent(temail))
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tname2)
                    .addComponent(tphoneno))
                .addGap(43, 43, 43)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tphoneno1)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        changePassword cp = new changePassword(username, true);
        cp.setVisible(true);
//        dispose();
//        int id = Integer.parseInt(tid.getText().toString());
//
//        String newPrice = newprice.getText().trim();
//        if (newPrice.equals("")){
//            JOptionPane.showMessageDialog(this, "Username and Password Should Not be Empty.", "Message", JOptionPane.ERROR_MESSAGE);
//        }
//        else{
//            int a = JOptionPane.showConfirmDialog(null, "New price will be "+newprice.getText()+" ?","Select",JOptionPane.YES_NO_OPTION);
//            if (a == 0){
//                userDao.updatePrice(newPrice, id);
//                clear();
//            }
//
//        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel t;
    private javax.swing.JLabel temail;
    private javax.swing.JLabel tid;
    private javax.swing.JLabel tname;
    private javax.swing.JLabel tname1;
    private javax.swing.JLabel tname2;
    private javax.swing.JLabel tname3;
    private javax.swing.JLabel tname4;
    private javax.swing.JLabel tphoneno;
    private javax.swing.JLabel tphoneno1;
    private javax.swing.JLabel tusername;
    // End of variables declaration//GEN-END:variables
}
